apiVersion: bobbycar.redhat.com/v1alpha1
kind: BobbycarZone
metadata:
  name: de-idstein-a3
spec:
  name: "Idstein A3"
  type: "circle"
  priority: 5
  position:
    lat: 50.19838330903354
    lng: 8.255592550250164
  radius: 800