---
global:
  openshift: true
  pattern: test
  localClusterDomain: apps.foo.cluster.com

clusterGroup:
  name: hub1

vault:
  injector:
    enabled: false
  ui:
    enabled: true
    serviceType: "LoadBalancer"
  server:
    route:
      host: null
      enabled: true
      tls:
        termination: "edge"
    image:
      repository: "registry.connect.redhat.com/hashicorp/vault"
      tag: "1.11.2-ubi"
