apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: car-sim-binding
  namespace: {{ .Release.Namespace }}
spec:
  params:
    - name: gitrevision
      value: $(body.after)
    - name: gitrepositoryurl
      value: $(body.repository.html_url)
    - name: contenttype
      value: $(header.Content-Type)
